# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: abacaba-orderer2
  labels:
    app: abacaba-orderer2
spec:
  serviceName: orderer2
  # Single instance of the Orderer Pod is needed
  replicas: 1
  selector:
    matchLabels:
      app: abacaba-orderer2
  template:
    metadata:
      labels:
        app: abacaba-orderer2
    spec:
      containers:
      - name: abacaba-orderer

        # Image used
        image: paramecium/k8s-hlf-abacaba-orderer2:2.0

        # Uncomment the following during development/testing of the image
        imagePullPolicy: Always
        env:
          # Points to the orderer.yaml
          - name: FABRIC_CFG_PATH
            value: /var/hyperledger/config
          # Level of logging
          - name: FABRIC_LOGGING_SPEC
            value: INFO
        volumeMounts:
        # This is pointing to the PVC
        - name: orderer2-ledger
          mountPath: /var/ledger
  volumeClaimTemplates:
  - metadata: 
      name: orderer2-ledger
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: general
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: abacaba-orderer2-clusterip

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)  
  selector:
    app: abacaba-orderer2

  ports:
    - name: abacaba-orderer2-clusterip
      port: 30750

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: abacaba-orderer2-nodeport

spec:
  selector:
    app: abacaba-orderer2

  ports:
    - name: abacaba-orderer2-nodeport
      port: 30750
      nodePort: 30650

  type: NodePort